// src/utils/mockData.ts
import { Product, Category, Banner } from '@/types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Mutfak', icon: '🍳', color: '#C8502A', productCount: 142 },
  { id: '2', name: 'Banyo', icon: '🛁', color: '#2C5F6E', productCount: 87 },
  { id: '3', name: 'Ev Tekstili', icon: '🛋️', color: '#7B5EA7', productCount: 203 },
  { id: '4', name: 'Dekorasyon', icon: '🪴', color: '#27AE60', productCount: 165 },
  { id: '5', name: 'Aydınlatma', icon: '💡', color: '#F0A500', productCount: 94 },
  { id: '6', name: 'Depolama', icon: '📦', color: '#E74C3C', productCount: 76 },
  { id: '7', name: 'Pişirme', icon: '🫕', color: '#E67E22', productCount: 118 },
  { id: '8', name: 'Servis', icon: '🍽️', color: '#1ABC9C', productCount: 99 },
];

export const BANNERS: Banner[] = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    title: 'Mutfağını Yenile',
    subtitle: '%40\'a varan indirim',
    ctaText: 'Hemen Alışveriş Yap',
    ctaLink: '/category/1',
    backgroundColor: '#C8502A',
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800',
    title: 'Ev Dekorasyonu',
    subtitle: 'Yeni koleksiyon geldi',
    ctaText: 'Keşfet',
    ctaLink: '/category/4',
    backgroundColor: '#2C5F6E',
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800',
    title: 'Banyo Aksesuarları',
    subtitle: 'Seçili ürünlerde %30 indirim',
    ctaText: 'İncele',
    ctaLink: '/category/2',
    backgroundColor: '#7B5EA7',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Granit Tencere Seti 5\'li',
    description: 'Granit kaplama, ergonomik sap, indüksiyonla uyumlu 5\'li tencere seti.',
    price: 899,
    originalPrice: 1299,
    discountPercent: 31,
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600',
    ],
    category: 'Mutfak',
    brand: 'KitchenPro',
    rating: 4.7,
    reviewCount: 342,
    stock: 25,
    isNew: false,
    isFeatured: true,
    tags: ['tencere', 'granit', 'set'],
    createdAt: '2024-01-15',
  },
  {
    id: 'p2',
    name: 'Cam Saklama Kabı Seti 8\'li',
    description: 'Hava geçirmez kapaklı, fırın ve bulaşık makinesine uyumlu cam saklama kapları.',
    price: 349,
    originalPrice: 499,
    discountPercent: 30,
    images: [
      'https://images.unsplash.com/photo-1612519000858-77e66d3b8ec8?w=600',
    ],
    category: 'Mutfak',
    brand: 'GlassCraft',
    rating: 4.5,
    reviewCount: 189,
    stock: 42,
    isNew: true,
    tags: ['saklama', 'cam', 'set'],
    createdAt: '2024-02-20',
  },
  {
    id: 'p3',
    name: 'Bambu Kesme Tahtası',
    description: 'Doğal bambu, antibakteriyal yüzey, 3 farklı boyut seçeneği.',
    price: 189,
    images: [
      'https://images.unsplash.com/photo-1614897153559-cc7e6c3b498f?w=600',
    ],
    category: 'Mutfak',
    brand: 'NatureCraft',
    rating: 4.8,
    reviewCount: 567,
    stock: 78,
    tags: ['bambu', 'kesme tahtası', 'doğal'],
    createdAt: '2024-01-10',
  },
  {
    id: 'p4',
    name: 'Dekoratif Mumluk Set 3\'lü',
    description: 'El yapımı, macun boyalı modern dekoratif mumluk seti.',
    price: 279,
    originalPrice: 359,
    discountPercent: 22,
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600',
    ],
    category: 'Dekorasyon',
    brand: 'ArtHome',
    rating: 4.6,
    reviewCount: 124,
    stock: 30,
    isNew: true,
    isFeatured: true,
    tags: ['mumluk', 'dekorasyon', 'el yapımı'],
    createdAt: '2024-03-01',
  },
  {
    id: 'p5',
    name: 'Paslanmaz Çelik Bıçak Seti 6\'lı',
    description: '18/8 paslanmaz çelik, ergonomik ahşap sap, manyetik bloklu.',
    price: 1249,
    originalPrice: 1699,
    discountPercent: 26,
    images: [
      'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600',
    ],
    category: 'Mutfak',
    brand: 'ChefEdge',
    rating: 4.9,
    reviewCount: 891,
    stock: 15,
    isFeatured: true,
    tags: ['bıçak', 'mutfak', 'çelik'],
    createdAt: '2023-12-01',
  },
  {
    id: 'p6',
    name: 'Rattan Depolama Sepeti',
    description: 'El örgüsü rattan, ahşap kulplu, 3 boy seçenek.',
    price: 219,
    images: [
      'https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=600',
    ],
    category: 'Depolama',
    brand: 'BohoHome',
    rating: 4.4,
    reviewCount: 203,
    stock: 55,
    tags: ['rattan', 'sepet', 'depolama'],
    createdAt: '2024-02-10',
  },
  {
    id: 'p7',
    name: 'Nordic Lamba - Bakır',
    description: 'Minimalist Nordic tasarım, E27 duy, tekstil kablo dahil.',
    price: 459,
    originalPrice: 589,
    discountPercent: 22,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600',
    ],
    category: 'Aydınlatma',
    brand: 'LightStudio',
    rating: 4.7,
    reviewCount: 156,
    stock: 20,
    isFeatured: true,
    tags: ['lamba', 'nordic', 'bakır'],
    createdAt: '2024-01-28',
  },
  {
    id: 'p8',
    name: 'Mermer Desenli Kahve Seti 6\'lı',
    description: 'Fine bone china, mermer baskı, altın jant detay.',
    price: 549,
    originalPrice: 699,
    discountPercent: 21,
    images: [
      'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600',
    ],
    category: 'Servis',
    brand: 'ElegantTable',
    rating: 4.8,
    reviewCount: 445,
    stock: 33,
    isFeatured: true,
    tags: ['kahve', 'fincan', 'mermer'],
    createdAt: '2023-11-15',
  },
];
